### ISSUE TITLE
Are you screwing with us with the last 2 versions?

### ISSUE THREAD

**Issue by stavros3006** [oklai/koala#605]
Version 2.1.0 was a trainwreck, v2.1.1 doesn't compile SASS files, but both suffer from the same two issues:
1. It takes forever to start the app on Windows 10 x64 (my Photoshop or Illustrator CC start 10 times faster)
2. The app is not registered and doesn't show up in the the Programs and Features list to be uninstalled!

**Comment by xMrKrisx** [comment]
is it true there's still no fix for the false directory issue after 2.1.1?

**Comment by zaygraveyard** [comment]
@xMrKrisx it is true, but I'm close to finding one (the false directory issue is fixed but an other issue poped up and that the one I'm trying to fix)
It's taking me more time to find a solution 'cause I'm on a mac and I'm having to use a virtual windows machine (which slows down my whole system)

**Comment by mrcoolbiz** [comment]
After updated to new version. 
It just keep saying "The system cannot find the path specified."
Even I downgrade to previous version, it still get the error.
I'm currently using window 10.

**Comment by stavros3006** [comment]
People, don't know about other platforms, but on Windows it even has other issues. It takes forever to start compared to v2.0.4 which starts in only a portion of a second (v2.1.1 takes around 50 seconds, almost a minute to start) and there is no option to uninstall it from Programs and features as it used to have.

**Comment by zaygraveyard** [comment]
@mrcoolbiz you downgraded to v2.0.4?

**Comment by timpowersdesign** [comment]
I've had this issue with both versions of v2.1 released on Win10 64bit. The uninstall.exe is located in the Program Files for anyone who wants to get rid of it.

Have no issues with 2.0.4 so have gone back to that in the meantime.

**Comment by mrcoolbiz** [comment]
Thank @zaygraveyard

**Comment by zaygraveyard** [comment]
@stavros3006 the startup delay has been fixed and will be in the next release
and as @timpowersdesgin pointed out the uninstaller is found in the `Koala.exe`'s directory.

**Comment by timpowersdesign** [comment]
It may be that the uninstaller is in the directory, but it's not at all helpful! Would much rather find it in the Add/Remove Programmes, or even the start menu.

**Comment by zaygraveyard** [comment]
Can anyone try this [v2.1.2](https://github.com/oklai/koala/releases/tag/v2.1.2)?

**Comment by hworm4** [comment]
@zaygraveyard  the v2.1.2 works perfectly 👍 fine .
the app now opens in seconds and The app is registered on Programs and Features
my OS Windows 10 x64

**Comment by Brett-Lee** [comment]
@zaygraveyard v2.1.2 solved the issue of slowly booting as well as the path can not be found error. 👍

**Comment by xMrKrisx** [comment]
I see everyone talking about v 2.1.2 but I dont see it...

**Comment by stavros3006** [comment]
@zaygraveyard I know that the uninstaller is in the directory, but older versions being able to be removed from Programs and features and the new one not is a minus feature in terms of a polished piece of software. :)

**Comment by zaygraveyard** [comment]
@xMrKrisx v2.1.2 is currently still in pre-release mode so Koala doesn't notify of it's existence (and it's not on the website either).
But you can find it in the releases page of this repo or by following the link I gave.

**Comment by srcreative-steveporter** [comment]
2.1.2 Beta works fine here

Any chance of a Auto Compile Toggle in the Settings?

**Comment by zaygraveyard** [comment]
@srcreative-steveporter Thanks
See #367 and #339 (this feature is next on the list)

**Comment by Pulsahr** [comment]
I can confirm this solves many of my issues.
There is still a minor bug. In original scss file I have:
```
/* Général
**************************************************/
```
The output has:
```
/* G├®n├®ral
**************************************************/
```
Both files are encoded in UTF-8 (without BOM) says Notepad++.

Want me to create a new issue ?

**Comment by zaygraveyard** [comment]
@Pulsahr yes please and thank you

**Comment by zaygraveyard** [comment]
@Pulsahr this is not an issue with Koala, SCSS files that contain UTF-8 characters require a `@charset "UTF-8";` at the beginning of the file.

**Comment by englishextra** [comment]
@zaygraveyard 
>SCSS files that contain UTF-8 characters require a @charset "UTF-8"; at the beginning of the file.
What's?

**Comment by zaygraveyard** [comment]
@englishextra 
`sass` requires it see sass/sass#1663
The original ruby [`sass`](https://github.com/sass/sass) is different than [`node-sass`](https://github.com/sass/node-sass) and Koala uses the original ruby `sass`.

**Comment by englishextra** [comment]
@zaygraveyard That's right

That said the dev has to place charset ath the top just fo the purpose of compiling with Koala, which may not acceptable at a particular setup. 

The tool is nice, but I had to stop using it because it may surprisingly damage you workflow, and wait for the autocompile to be resolved. Thanks.

**Comment by zaygraveyard** [comment]
@englishextra 
After more digging I found [the encodings section](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#encodings) in the SASS documentation.
And it appears SASS will check the Ruby string encoding.
So I will force the Ruby string encoding to UTF-8 in the next version hopefully this will help.

**Comment by englishextra** [comment]
@zaygraveyard Thanks a lot.
